### PR TITLE
Requires fully-formed Slack names for audience

### LINKED ISSUE #63: Require `@` for audience setting
Using the `@` makes sure that the db has the Slack-official version of the audience, which should help avoid unexpected behavior.

For example: `@standup-bot audience testgroup` will save the audience as `testgroup`, whereas `@standup-bot audience @testgroup` will save the audience as something like `<!subteam^S234MGM|@testgroup>`.

### PR DESCRIPTION
**Pull request by mgwalker**
E.g., `@here`, `@channel`, `@user-group`.  That way they can be stored as proper IDs and will keep working even if the usergroup name changes.

Closes #63

### CODE REVIEW

**Comment by stvnrlly** [comment]
Originally, I probably left out the `@` to avoid notifications, but it probably makes sense to alert anybody in the relevant group that they'll be getting that notification in the future.

File: lib/bot/setAudience.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ function setUserGroup(bot, message) {
 }
 
 function attachListener(controller) {
-  controller.hears(['(usergroup|audience) (\\S*)'],['direct_mention'], setUserGroup);
+  controller.hears(['(usergroup|audience) (<!(subteam|here|channel).*>)'],['direct_mention'], setUserGroup);
```
Comment (stvnrlly) [inline lib/bot/setAudience.js]: Should `.*` be set to be non-greedy, to avoid the unlikely scenario where there's a `>` somewhere later in the message?

Comment (mgwalker) [reply lib/bot/setAudience.js]: Yep, good catch.

**Review by stvnrlly — APPROVED** [review]
